spring.application.name=JobManagementSvc

server.servlet.context-path=/job-api
server.port=8081
#http://localhost:{{server.port}}/{{server.servlet.context-path}}/swagger-ui/index.html#/
#http://localhost:8080/job-api/swagger-ui/index.html#/

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:rjanytest
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#spring.security.user.name=eureka
#spring.security.user.password=eureka-test
#
#eureka.instance.preferIpAddress=true
